/**
 * NPC Template Data
 *
 * Extracted system templates from NPCTemplateService to reduce file complexity
 */

import { NPCTemplate } from '@/types/npc';

export const SYSTEM_TEMPLATES: NPCTemplate[] = [
  {
    id: 'system-guard-basic',
    name: 'Guard',
    category: 'humanoid',
    challengeRating: 0.125,
    size: 'medium',
    stats: {
      abilityScores: {
        strength: 13,
        dexterity: 12,
        constitution: 12,
        intelligence: 10,
        wisdom: 11,
        charisma: 10,
      },
      hitPoints: { maximum: 11, current: 11, temporary: 0 },
      armorClass: 16,
      speed: 30,
      proficiencyBonus: 2,
      savingThrows: {},
      skills: { perception: 2 },
      damageVulnerabilities: [],
      damageResistances: [],
      damageImmunities: [],
      conditionImmunities: [],
      senses: [],
      languages: ['Common'],
    },
    equipment: [
      { name: 'Chain shirt', type: 'armor', quantity: 1, magical: false },
      { name: 'Shield', type: 'armor', quantity: 1, magical: false },
      { name: 'Spear', type: 'weapon', quantity: 1, magical: false },
    ],
    spells: [],
    actions: [
      {
        name: 'Spear',
        type: 'action',
        description: 'Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6 + 1) piercing damage.',
        attackBonus: 3,
        damage: '1d6+1 piercing',
        range: '5 ft. or 20/60 ft.',
      },
    ],
    behavior: {
      personality: 'Disciplined and alert',
      motivations: 'Protect assigned area or person',
      tactics: 'Calls for help, fights defensively',
    },
    isSystem: true,
  },
  {
    id: 'system-goblin-basic',
    name: 'Goblin',
    category: 'humanoid',
    challengeRating: 0.25,
    size: 'small',
    stats: {
      abilityScores: {
        strength: 8,
        dexterity: 14,
        constitution: 10,
        intelligence: 10,
        wisdom: 8,
        charisma: 8,
      },
      hitPoints: { maximum: 7, current: 7, temporary: 0, hitDice: '2d6' },
      armorClass: 15,
      speed: 30,
      proficiencyBonus: 2,
      savingThrows: {},
      skills: { stealth: 6 },
      damageVulnerabilities: [],
      damageResistances: [],
      damageImmunities: [],
      conditionImmunities: [],
      senses: ['Darkvision 60 ft.'],
      languages: ['Common', 'Goblin'],
    },
    equipment: [
      { name: 'Leather armor', type: 'armor', quantity: 1, magical: false },
      { name: 'Shield', type: 'armor', quantity: 1, magical: false },
      { name: 'Scimitar', type: 'weapon', quantity: 1, magical: false },
      { name: 'Shortbow', type: 'weapon', quantity: 1, magical: false },
      { name: 'Arrows', quantity: 20, type: 'weapon', magical: false },
    ],
    spells: [],
    actions: [
      {
        name: 'Scimitar',
        type: 'action',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.',
        attackBonus: 4,
        damage: '1d6+2 slashing',
        range: '5 ft.',
      },
      {
        name: 'Shortbow',
        type: 'action',
        description: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackBonus: 4,
        damage: '1d6+2 piercing',
        range: '80/320 ft.',
      },
    ],
    behavior: {
      personality: 'Sneaky and cowardly',
      motivations: 'Survival and treasure',
      tactics: 'Uses stealth, attacks from range, flees when outnumbered',
    },
    isSystem: true,
  },
  {
    id: 'system-orc-basic',
    name: 'Orc',
    category: 'humanoid',
    challengeRating: 1,
    size: 'medium',
    stats: {
      abilityScores: {
        strength: 16,
        dexterity: 12,
        constitution: 16,
        intelligence: 7,
        wisdom: 11,
        charisma: 10,
      },
      hitPoints: { maximum: 15, current: 15, temporary: 0, hitDice: '2d8+6' },
      armorClass: 13,
      speed: 30,
      proficiencyBonus: 2,
      savingThrows: {},
      skills: { intimidation: 2 },
      damageVulnerabilities: [],
      damageResistances: [],
      damageImmunities: [],
      conditionImmunities: [],
      senses: ['Darkvision 60 ft.'],
      languages: ['Common', 'Orc'],
    },
    equipment: [
      { name: 'Hide armor', type: 'armor', quantity: 1, magical: false },
      { name: 'Greataxe', type: 'weapon', quantity: 1, magical: false },
      { name: 'Javelin', quantity: 4, type: 'weapon', magical: false },
    ],
    spells: [],
    actions: [
      {
        name: 'Greataxe',
        type: 'action',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage.',
        attackBonus: 5,
        damage: '1d12+3 slashing',
        range: '5 ft.',
      },
      {
        name: 'Javelin',
        type: 'action',
        description: 'Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 6 (1d6 + 3) piercing damage.',
        attackBonus: 5,
        damage: '1d6+3 piercing',
        range: '5 ft. or 30/120 ft.',
      },
    ],
    behavior: {
      personality: 'Aggressive and brutal',
      motivations: 'Violence and conquest',
      tactics: 'Charges into melee, fights to the death',
    },
    isSystem: true,
  },
  {
    id: 'system-skeleton-basic',
    name: 'Skeleton',
    category: 'undead',
    challengeRating: 0.25,
    size: 'medium',
    stats: {
      abilityScores: {
        strength: 10,
        dexterity: 14,
        constitution: 15,
        intelligence: 6,
        wisdom: 8,
        charisma: 5,
      },
      hitPoints: { maximum: 13, current: 13, temporary: 0, hitDice: '2d8+4' },
      armorClass: 13,
      speed: 30,
      proficiencyBonus: 2,
      savingThrows: {},
      skills: {},
      damageVulnerabilities: ['bludgeoning'],
      damageResistances: [],
      damageImmunities: ['poison'],
      conditionImmunities: ['exhaustion', 'poisoned'],
      senses: ['Darkvision 60 ft.'],
      languages: [],
    },
    equipment: [
      { name: 'Armor scraps', type: 'armor', quantity: 1, magical: false },
      { name: 'Shortsword', type: 'weapon', quantity: 1, magical: false },
      { name: 'Shortbow', type: 'weapon', quantity: 1, magical: false },
      { name: 'Arrows', quantity: 20, type: 'weapon', magical: false },
    ],
    spells: [],
    actions: [
      {
        name: 'Shortsword',
        type: 'action',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackBonus: 4,
        damage: '1d6+2 piercing',
        range: '5 ft.',
      },
      {
        name: 'Shortbow',
        type: 'action',
        description: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackBonus: 4,
        damage: '1d6+2 piercing',
        range: '80/320 ft.',
      },
    ],
    behavior: {
      personality: 'Mindless undead',
      motivations: 'Follows creator\'s commands',
      tactics: 'Attacks until destroyed',
    },
    isSystem: true,
  },
  {
    id: 'system-wolf-basic',
    name: 'Wolf',
    category: 'beast',
    challengeRating: 0.25,
    size: 'medium',
    stats: {
      abilityScores: {
        strength: 12,
        dexterity: 15,
        constitution: 12,
        intelligence: 3,
        wisdom: 12,
        charisma: 6,
      },
      hitPoints: { maximum: 11, current: 11, temporary: 0, hitDice: '2d8+2' },
      armorClass: 13,
      speed: 40,
      proficiencyBonus: 2,
      savingThrows: {},
      skills: { perception: 3, stealth: 4 },
      damageVulnerabilities: [],
      damageResistances: [],
      damageImmunities: [],
      conditionImmunities: [],
      senses: ['Keen hearing and smell'],
      languages: [],
    },
    equipment: [],
    spells: [],
    actions: [
      {
        name: 'Bite',
        type: 'action',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.',
        attackBonus: 4,
        damage: '2d4+2 piercing',
        range: '5 ft.',
        savingThrow: { ability: 'strength', dc: 11 },
      },
    ],
    behavior: {
      personality: 'Pack hunter',
      motivations: 'Hunt for food',
      tactics: 'Works with pack to surround prey',
    },
    isSystem: true,
  },
];